export const dsReview = [
  {
    id: 1,
    img: "https://skillslash-cdn.s3.ap-south-1.amazonaws.com/static/web/Mirnal_sahay_review.webp",
    name: "Mrinal Sahay",
    alt: "Mrinal Sahay review",
    rating: "high",
    para: "One of the best course providers is Skillslash, their data  science course has helped me become the data",
    desc: "One of the best course providers is Skillslash, their data science course has helped me become the data scientist I am today. There are tons of differences  between studying data science and working as a data  scientist.",
  },
  {
    id: 2,
    img: "https://skillslash-cdn.s3.ap-south-1.amazonaws.com/static/web/Gautum_skillslash_review.webp",
    name: "Gautam",
    alt: "Gautam review",
    rating: "high",
    para: " One of the best platform for working professionals. Although a new startup but training quality scientist I am today.",
    desc: " One of the best platform for working professionals. Although a  new startup but training quality scientist I am today.There are tons of differences between studying data science and working as a data scientist.",
  },
  {
    id: 3,
    img: "https://skillslash-cdn.s3.ap-south-1.amazonaws.com/static/web/sameer-ahemed-skillslash-review.webp",
    name: "Sammer Ahmed",
    alt: "Sammer Ahmed review",
    rating: "high",
    para: " Skillslash is truly one of the best institutes to study machine learning, I thank my brother for suggesting me",
    desc: " Skillslash is truly one of the best institutes to study machine learning, I thank my brother for suggesting me this course. The course has amazing perks for working    professionals like live classes, faculty of industry professionals",
  },
  {
    id: 4,
    img: "https://skillslash-cdn.s3.ap-south-1.amazonaws.com/static/web/Tilak-rao-skillslash-review.webp",
    name: "Tilak Rao",
    alt: "Tilak Rao review",
    rating: "medium",
    para: "AI and ML full stack program is too good and helpful for working professionals, I have done BCA so I was",
    desc: "AI and ML full stack program is too good and helpful for working professionals, I have done BCA so I was well versed in Java, C, basic SQL and C++. At Skillslash I learnt Python, core SQL, R, math - stats, ML and More.",
  },
  {
    id: 5,
    img: "https://skillslash-cdn.s3.ap-south-1.amazonaws.com/static/web/New-UI/priya-khatun-data-science-review.webp",
    name: "Priya Khatun",
    alt: "Priya Khatin",
    rating: "medium",
    para: "The instructor are very friendly and cheerful. They thought us amazing knowledge about how to create components.",
    desc: "The instructor are very friendly and cheerful. They thought us amazing knowledge about how to create components. the session was good. They start from basic and it is an perfect learning for freshers. Thank you Skillslash Academy..!",
  },
  {
    id: 6,
    img: "https://skillslash-cdn.s3.ap-south-1.amazonaws.com/static/web/New-UI/priya-khatun-data-science-review.webp",
    name: "Krishan Gupta",
    alt: "Krishan Gupta",
    rating: "medium",
    para: "It's was overall a good experience to attend Priyanka mam class about practical hands-on class on data visualization",
    desc: "It's was overall a good experience to attend Priyanka mam class about practical hands-on class on data visualization tool called as Tableau.. Thanks for your valuable time and special thanks to skillslash academy for such a fantastic initiative.",
  },
  {
    id: 7,
    img: "https://skillslash-cdn.s3.ap-south-1.amazonaws.com/static/web/New-UI/rishi-data-science-review.webp",
    name: "Rishi Bhaisare",
    alt: "Rishi Bhaisare",
    rating: "medium",
    para: "Training for Data Visualisation with Tableau was really amazing. Got to learn a new skill and the trainer",
    desc: "Training for Data Visualisation with Tableau was really amazing. Got to learn a new skill and the trainer made sure the learning process goes smooth even for people with non technical background.Looking forward for more sessions with SkillSlash.",
  },
  {
    id: 8,
    img: "https://skillslash-cdn.s3.ap-south-1.amazonaws.com/static/web/New-UI/ashmita-data-science-review.webp",
    name: "Ashmita Chakraborty",
    alt: "Ashmita Chakraborty",
    rating: "medium",
    para: "Training for Data Visualisation with Tableau was really amazing. Got to learn a new skill and the trainer",
    desc: "Being a fresher it's really very helpful if someone makes you feel comfortable when you're learning it from scratch.  My experience for SQL session was something like that. Tutor took good care for the concepts, hands on, assignment and most importantly doubt clearing. Looking forward for your classes like this Skillslash Academy.",
  },
  {
    id: 9,
    img: "https://skillslash-cdn.s3.ap-south-1.amazonaws.com/static/web/New-UI/JayeshRajPrasadReviewBA.webp",
    name: "Jayesh Raj Prasad",
    alt: "Jayesh Raj Prasad",
    rating: "medium",
    para: "I had attended their Data Science course .They had provided all the lectures on Python,  Sql , Tableau...",
    desc: "I had attended their Data Science course .They had provided all the lectures on Python,  Sql , Tableau , power BI , Excel and more . The quality of content they provide was very good, mentor was very polite and responsible. The example problems and their assignments were awesome. I recommend you to take courses in skillslash .",
  },
  {
    id: 10,
    img: "https://skillslash-cdn.s3.ap-south-1.amazonaws.com/static/web/New-UI/AkshayaSobananReviewBA.webp",
    name: "Akshaya Sobanan",
    alt: "Akshaya Sobanan",
    rating: "medium",
    para: "Skillslash,  I have attended 2 sessions of Power BI workshop. It was helpful for me and useful as I was...",
    desc: "Skillslash,  I have attended 2 sessions of Power BI workshop. It was helpful for me and useful as I was planning to begin Data Science journey.  The session was clear and the instructor gave pauses and cleared doubts  in every 15-20 mins interval and I am eager to learn more about it.",
  },
  {
    id: 11,
    img: "https://skillslash-cdn.s3.ap-south-1.amazonaws.com/static/web/New-UI/BadkasPoorviReviewBA.webp",
    name: "Badkas Poorvi",
    alt: "Badkas Poorvi",
    rating: "medium",
    para: "I attended one Power BI session ,the faculty was good and the explanation about basic was too long but good...",
    desc: "I attended one Power BI session ,the faculty was good and the explanation about basic was too long but good... Some of them were not even demo... The workshop was having some assignments that helped me to clear my doubts ...",
  },
  {
    id: 12,
    img: "https://skillslash-cdn.s3.ap-south-1.amazonaws.com/static/web/New-UI/NahazNabbuReviewBA.webp",
    name: "Nahaz Nabbu",
    alt: "Nahaz Nabbu",
    rating: "medium",
    para: "The session on Power BI for Data Science was awesome. I have learnt a lot from the workshop from basic..",
    desc: "The session on Power BI for Data Science was awesome. I have learnt a lot from the workshop from basic to intermediate. The tutor had explained point to point & made us understand in proper manner. I highly recommend skillslash for these kind of session or courses.",
  },

  {
    id: 14,
    img: "https://skillslash-cdn.s3.ap-south-1.amazonaws.com/static/web/New-UI/PrathanapatelReviewBA.webp",
    name: "Prathana Patel",
    alt: "Prathana Patel",
    rating: "medium",
    para: "The Session was  Awesome.Thanks a lot Skillslash Family.Many new things learned during these sessions...",
    desc: "The Session was  Awesome.Thanks a lot Skillslash Family.Many new things learned during these sessions and know the power of Tableau in data visualisation.It was really a great learning experience. The interaction & solving the doubts of the students are really nice! Thank you so much for conducted the webinar.",
  },
  {
    id: 15,
    img: "https://skillslash-cdn.s3.ap-south-1.amazonaws.com/static/web/New-UI/SumanthReviewBA.webp",
    name: "SUMANTH KOLLURI",
    alt: "SUMANTH KOLLURI",
    rating: "medium",
    para: "The Session was  Awesome.Thanks a lot Skillslash Family.Many new things learned during these...",
    desc: "Very useful information and gave me a foundational base in business analysis and analytics and now i have clear overview of this career and the possible option. This course help me to understand what is data analytics and its job functions.. great course.",
  },
];
export const webReview = [
  {
    id: 1,
    img: "https://skillslash-cdn.s3.ap-south-1.amazonaws.com/static/web/satya agravarapu-web-development-review.png",
    name: "satya agravarapu",
    alt: "satya agravarapu review",
    rating: "high",
    para: " I have done a course in javascript/React. The quality of        content they provide was very good, mentor was very polite,        responsible",
    desc: " I have done a course in javascript/React. The quality of content they provide was very good, mentor was very polite, responsible and interesting to learn.The example problems and their        assignments were doing good. I gained more knowledge aboubt react. I feel it's worthy to spend my time for this course. I recommend you to take courses in skill slash.",
  },
  {
    id: 2,
    img: "https://skillslash-cdn.s3.ap-south-1.amazonaws.com/static/web/SHASHIKANT SAI-web-development-review.png",
    name: "Shashikant Sai",
    alt: "Shashikant Sai review",
    rating: "high",
    para: " I have attended sessions on react js. The proctors are very friendly and cheerful. They thought us amazing knowledge about  how to create components.",
    desc: " I have attended sessions on react js. The proctors are very  friendly and cheerful. They thought us amazing knowledge about   how to create components. the session was good. They start from basic and it is an    perfect learning for freshers. Thank you Skillslash    Academy for this sessions..!",
  },
  {
    id: 3,
    img: "https://skillslash-cdn.s3.ap-south-1.amazonaws.com/static/web/spoorti-v-web-development-review.png",
    name: "Spoorti v",
    alt: "spoorti v review",
    rating: "high",
    para: " I had attended React JS session The overall session was    awesome and was very useful for beginners. Expecting stil    more sessions",
    desc: " I had attended React JS session The overall session was    awesome and was very useful for beginners. Expecting still    more sessions on latest technical language",
  },

  {
    id: 5,
    img: "https://skillslash-cdn.s3.ap-south-1.amazonaws.com/static/web/Pravin-Kumar-web-development-review.png",
    name: "Pravin Kumar",
    alt: "pravin kumar review",
    rating: "high",
    para: "  Skillslash Provides Variety Of Bootcamps On Latest Technology    Which Helps Many Students And Work Professional To Learn New    Skills",
    desc: "  Skillslash Provides Variety Of Bootcamps On Latest Technology    Which Helps Many Students And Work Professional To Learn New Skills  And Improve Theire Knowledge. I Have Attend One Of Thier    Bootcamp On Reactjs And I Got To know About Some New    Concept Of Reactjs, It Was Really A Good Experience",
  },
  {
    id: 6,
    img: "https://skillslash-cdn.s3.ap-south-1.amazonaws.com/static/web/Brijisha-Doshi-webdevelopment-review.png",
    name: "Brijisha Doshi",
    alt: "Brijisha Doshi review",
    rating: "high",
    para: "  I have attended React.js course..It was amazing. All concepts    about React js were explained nicely. Thank you Skillslash ",
    desc: "  I have attended React.js course..It was amazing. All concepts    about React js were explained nicely. Thank you Skillslash ",
  },
  {
    id: 7,
    img: "https://skillslash-cdn.s3.ap-south-1.amazonaws.com/static/web/Harshal-Chougule-web-development-review.png",
    name: "Harshal Chougule",
    alt: "Harshal Chougule review",
    rating: "medium",
    para: " I have attended 2 sessions of react js. The proctors are very   friendly and cheerful. They thought us amazing knowledge about",
    desc: "I have attended 2 sessions of react js. The proctors are very    friendly and cheerful. They thought us amazing knowledge about how to create components and use of data structure. You    should also join upcoming sessions of skill slash for    improving your skills.",
  },
  {
    id: 8,
    img: "https://skillslash-cdn.s3.ap-south-1.amazonaws.com/static/web/Merlin Thomas-web-development-review.png",
    name: "Merlin Thomas",
    alt: "Merlin Thomas review",
    rating: "medium",
    para: " I have attended React js sessions and the session was good.It was a great session by Skillslash Academy. The way of teaching is very..",
    desc: " I have attended React js sessions and the session was good.It was a great session by Skillslash Academy. The way of teaching is very  good. They start from basic and it is an perfect learning for freshers. Thank you Skillslash Academy for this sessions.",
  },
  {
    id: 9,
    img: "https://skillslash-cdn.s3.ap-south-1.amazonaws.com/static/web/Prarthana-Thokal-web-development-review.png",
    name: "Prarthana Thokal",
    alt: "Prarthana Thokal review",
    rating: "low",
    para: " I had attended sessions on SQL..All that sessions really helped me to brush up my knowledge to very extent..",
    desc: " I had attended sessions on SQL..All that sessions really helped me to brush up my knowledge to very extent. Tutor covered all the topics very well & also made the sessions more interactive.. I feel so worthy to spend my time on this sessions.",
  },
];
export const fsReview = [
  {
    id: 1,
    img: "https://skillslash-cdn.s3.ap-south-1.amazonaws.com/static/web/PANKAJ_CHOWDHURY.webp",
    name: "Pankaj Chowdhury",
    alt: "Pankaj Chowdhury review",
    rating: "high",
    para: "The trainers at Skillslash are quite amazing. The teaching style was simple yet effective. I was able to get into my dream company IBM within 7 months",
    desc: "The trainers at Skillslash are quite amazing. The teaching style was simple yet effective. I was able to get into my dream company IBM within 7 months The trainers at Skillslash are quite amazing. The teaching style was simple yet effective. I was able to get into my dream company IBM within 7 months",
  },

  {
    id: 3,
    img: "https://skillslash-cdn.s3.ap-south-1.amazonaws.com/static/web/Manisha_singh.webp",
    name: "Manisha Singh",
    alt: "Manisha singh review",
    rating: "high",
    para: " I wanted to brush up my full stack skills when I joined Skillslash program. I had been in a software role and this course helped me improve my",
    desc: " I wanted to brush up my full stack skills when I joined Skillslash program. I had been in a software role and this course helped me improve my weak areas significantly. Mentors were amazing and the interview prep module really helped me become more confident in interviews. Got multiple offers in a period of 3 months, thanks to Skillslash..",
  },
  {
    id: 4,
    img: "https://skillslash-cdn.s3.ap-south-1.amazonaws.com/static/web/Muralikrishna_Alichetty.webp",
    name: "Muralikrishna",
    alt: "Muralikrishna review",
    rating: "medium",
    para: " The reason I joined Skillslash was because of the Data engineering and Cloud specialisation. The course was quite helpful as I was able to",
    desc: "The reason I joined Skillslash was because of the Data engineering and Cloud specialisation. The course was quite helpful as I was able to  get a Senior DBA role at the end of the program. Interview preparation module was also very helpful as I was able to build a strong portfolio as a result of this.",
  },
  {
    id: 5,
    img: "https://skillslash-cdn.s3.ap-south-1.amazonaws.com/static/web/GIRISH_BALLAMPALLI.webp",
    name: "Girisih",
    alt: "Girisih review",
    rating: "medium",
    para: " I think Dhaval has clear understanding of whatever he teach,wheher it is Data Structures, Algorithms, Dynamic Programming,",
    desc: "I think Dhaval has clear understanding of whatever he teach,wheher it is Data Structures, Algorithms, Dynamic Programming,  he explains with such ease that even hard problem seems easy. Hats off to his teaching and Dhaval keep on motivating and helping othersh really gave my preparation a solid boost.",
  },
  {
    id: 6,
    img: "https://skillslash-cdn.s3.ap-south-1.amazonaws.com/static/web/Anukalp_Desai.webp",
    name: "Anukalp Desai",
    alt: "Anukalp Desai review",
    rating: "low",
    para: "I have taken data structures and algorithms course taught by Dhaval, he is very accessible and does an amazing job at making",
    desc: "I have taken data structures and algorithms course taught by Dhaval, he is very accessible and does an amazing job at making difficult concepts easily understandable.",
  },
  {
    id: 7,
    img: "https://skillslash-cdn.s3.ap-south-1.amazonaws.com/static/web/Anurag_Sinha.webp",
    name: "Anurag Sinha",
    alt: "Anurag Sinha review",
    rating: "medium",
    para: "Dhawal Sir is a really great mentor. He helped me identify my weak areas and work on it consistently. He was always supportive and his style",
    desc: "Dhawal Sir is a really great mentor. He helped me identify my weak areas and work on it consistently. He was always supportive and his style  of teaching kept hinged to my goals. I was able to crack a senior software role as a result of that and I will always be thankful for all his support and guidance.",
  },
  {
    id: 8,
    img: "https://skillslash-cdn.s3.ap-south-1.amazonaws.com/static/web/Ankur_Singh.webp",
    name: "Ankur Singh",
    alt: "Ankur review",
    rating: "low",
    para: "The course structure was really good and covered most of the topics like Linked list, trees , graphs, recursion, dynamic programming etc.",
    desc: "The course structure was really good and covered most of the topics like Linked list, trees , graphs, recursion, dynamic programming etc.  Dhaval Sir did a great job taking each topic to a great clarity level. Rather than remembering the solution to the problem, he taught me how to approach problem and solve it.",
  },
];
export const homeReview = [
  {
    id: 1,
    img: "https://skillslash-cdn.s3.ap-south-1.amazonaws.com/static/web/Mirnal_sahay_review.webp",
    name: "Mrinal Sahay",
    alt: "Mrinal Sahay review",
    rating: "high",
    para: "One of the best course providers is Skillslash, their data  science course has helped me become the data",
    desc: "One of the best course providers is Skillslash, their data science course has helped me become the data scientist I am today. There are tons of differences  between studying data science and working as a data  scientist.",
  },
  {
    id: 2,
    img: "https://skillslash-cdn.s3.ap-south-1.amazonaws.com/static/web/Gautum_skillslash_review.webp",
    name: "Gautam",
    alt: "Gautam review",
    rating: "high",
    para: " One of the best platform for working professionals. Although a new startup but training quality scientist I am today.",
    desc: " One of the best platform for working professionals. Although a  new startup but training quality scientist I am today.There are tons of differences between studying data science and working as a data scientist.",
  },
  {
    id: 3,
    img: "https://skillslash-cdn.s3.ap-south-1.amazonaws.com/static/web/sameer-ahemed-skillslash-review.webp",
    name: "Sammer Ahmed",
    alt: "Sammer Ahmed review",
    rating: "high",
    para: " Skillslash is truly one of the best institutes to study machine learning, I thank my brother for suggesting me",
    desc: " Skillslash is truly one of the best institutes to study machine learning, I thank my brother for suggesting me this course. The course has amazing perks for working    professionals like live classes, faculty of industry professionals",
  },
  {
    id: 4,
    img: "https://skillslash-cdn.s3.ap-south-1.amazonaws.com/static/web/Tilak-rao-skillslash-review.webp",
    name: "Tilak Rao",
    alt: "Tilak Rao review",
    rating: "medium",
    para: "AI and ML full stack program is too good and helpful for working professionals, I have done BCA so I was",
    desc: "AI and ML full stack program is too good and helpful for working professionals, I have done BCA so I was well versed in Java, C, basic SQL and C++. At Skillslash I learnt Python, core SQL, R, math - stats, ML and More.",
  },
  {
    id: 5,
    img: "https://skillslash-cdn.s3.ap-south-1.amazonaws.com/static/web/satya agravarapu-web-development-review.png",
    name: "satya agravarapu",
    alt: "satya agravarapu review",
    rating: "high",
    para: " I have done a course in javascript/React. The quality of        content they provide was very good, mentor was very polite,        responsible",
    desc: " I have done a course in javascript/React. The quality of content they provide was very good, mentor was very polite, responsible and interesting to learn.The example problems and their        assignments were doing good. I gained more knowledge aboubt react. I feel it's worthy to spend my time for this course. I recommend you to take courses in skill slash.",
  },
  {
    id: 6,
    img: "https://skillslash-cdn.s3.ap-south-1.amazonaws.com/static/web/SHASHIKANT SAI-web-development-review.png",
    name: "Shashikant Sai",
    alt: "Shashikant Sai review",
    rating: "high",
    para: " I have attended sessions on react js. The proctors are very friendly and cheerful. They thought us amazing knowledge about  how to create components.",
    desc: " I have attended sessions on react js. The proctors are very  friendly and cheerful. They thought us amazing knowledge about   how to create components. the session was good. They start from basic and it is an    perfect learning for freshers. Thank you Skillslash    Academy for this sessions..!",
  },
  {
    id: 7,
    img: "https://skillslash-cdn.s3.ap-south-1.amazonaws.com/static/web/spoorti-v-web-development-review.png",
    name: "Spoorti v",
    alt: "spoorti v review",
    rating: "high",
    para: " I had attended React JS session The overall session was    awesome and was very useful for beginners. Expecting stil    more sessions",
    desc: " I had attended React JS session The overall session was    awesome and was very useful for beginners. Expecting still    more sessions on latest technical language",
  },

  {
    id: 8,
    img: "https://skillslash-cdn.s3.ap-south-1.amazonaws.com/static/web/Pravin-Kumar-web-development-review.png",
    name: "Pravin Kumar",
    alt: "pravin kumar review",
    rating: "high",
    para: "  Skillslash Provides Variety Of Bootcamps On Latest Technology    Which Helps Many Students And Work Professional To Learn New    Skills",
    desc: "  Skillslash Provides Variety Of Bootcamps On Latest Technology    Which Helps Many Students And Work Professional To Learn New Skills  And Improve Theire Knowledge. I Have Attend One Of Thier    Bootcamp On Reactjs And I Got To know About Some New    Concept Of Reactjs, It Was Really A Good Experience",
  },
  {
    id: 9,
    img: "https://skillslash-cdn.s3.ap-south-1.amazonaws.com/static/web/Brijisha-Doshi-webdevelopment-review.png",
    name: "Brijisha Doshi",
    alt: "Brijisha Doshi review",
    rating: "high",
    para: "  I have attended React.js course..It was amazing. All concepts    about React js were explained nicely. Thank you Skillslash ",
    desc: "  I have attended React.js course..It was amazing. All concepts    about React js were explained nicely. Thank you Skillslash ",
  },
  {
    id: 10,
    img: "https://skillslash-cdn.s3.ap-south-1.amazonaws.com/static/web/Harshal-Chougule-web-development-review.png",
    name: "Harshal Chougule",
    alt: "Harshal Chougule review",
    rating: "medium",
    para: " I have attended 2 sessions of react js. The proctors are very   friendly and cheerful. They thought us amazing knowledge about",
    desc: "I have attended 2 sessions of react js. The proctors are very    friendly and cheerful. They thought us amazing knowledge about how to create components and use of data structure. You    should also join upcoming sessions of skill slash for    improving your skills.",
  },
  {
    id: 11,
    img: "https://skillslash-cdn.s3.ap-south-1.amazonaws.com/static/web/Merlin Thomas-web-development-review.png",
    name: "Merlin Thomas",
    alt: "Merlin Thomas review",
    rating: "medium",
    para: " I have attended React js sessions and the session was good.It was a great session by Skillslash Academy. The way of teaching is very..",
    desc: " I have attended React js sessions and the session was good.It was a great session by Skillslash Academy. The way of teaching is very  good. They start from basic and it is an perfect learning for freshers. Thank you Skillslash Academy for this sessions.",
  },
  {
    id: 12,
    img: "https://skillslash-cdn.s3.ap-south-1.amazonaws.com/static/web/Prarthana-Thokal-web-development-review.png",
    name: "Prarthana Thokal",
    alt: "Prarthana Thokal review",
    rating: "low",
    para: " I had attended sessions on SQL..All that sessions really helped me to brush up my knowledge to very extent..",
    desc: " I had attended sessions on SQL..All that sessions really helped me to brush up my knowledge to very extent. Tutor covered all the topics very well & also made the sessions more interactive.. I feel so worthy to spend my time on this sessions.",
  },
  {
    id: 13,
    img: "https://skillslash-cdn.s3.ap-south-1.amazonaws.com/static/web/PANKAJ_CHOWDHURY.webp",
    name: "Pankaj Chowdhury",
    alt: "Pankaj Chowdhury review",
    rating: "high",
    para: "The trainers at Skillslash are quite amazing. The teaching style was simple yet effective. I was able to get into my dream company IBM within 7 months",
    desc: "The trainers at Skillslash are quite amazing. The teaching style was simple yet effective. I was able to get into my dream company IBM within 7 months The trainers at Skillslash are quite amazing. The teaching style was simple yet effective. I was able to get into my dream company IBM within 7 months",
  },
  {
    id: 14,
    img: "https://skillslash-cdn.s3.ap-south-1.amazonaws.com/static/web/Mirnal_sahay_review.webp",
    name: "Mrinal Sahay",
    alt: "Mrinal Sahay review",
    rating: "high",
    para: "The trainers at Skillslash are quite amazing. The teaching style was simple yet effective. I was able to get into my dream company IBM within 7 months",
    desc: "One of the best course providers is Skillslash, their data science course has helped me become the data scientist I am today. There are tons of differences  between studying data science and working as a data  scientist.",
  },
  {
    id: 15,
    img: "https://skillslash-cdn.s3.ap-south-1.amazonaws.com/static/web/Manisha_singh.webp",
    name: "Manisha Singh",
    alt: "Manisha singh review",
    rating: "high",
    para: " I wanted to brush up my full stack skills when I joined Skillslash program. I had been in a software role and this course helped me improve my",
    desc: " I wanted to brush up my full stack skills when I joined Skillslash program. I had been in a software role and this course helped me improve my weak areas significantly. Mentors were amazing and the interview prep module really helped me become more confident in interviews. Got multiple offers in a period of 3 months, thanks to Skillslash..",
  },
  {
    id: 16,
    img: "https://skillslash-cdn.s3.ap-south-1.amazonaws.com/static/web/Muralikrishna_Alichetty.webp",
    name: "Muralikrishna",
    alt: "Muralikrishna review",
    rating: "medium",
    para: " The reason I joined Skillslash was because of the Data engineering and Cloud specialisation. The course was quite helpful as I was able to",
    desc: "The reason I joined Skillslash was because of the Data engineering and Cloud specialisation. The course was quite helpful as I was able to  get a Senior DBA role at the end of the program. Interview preparation module was also very helpful as I was able to build a strong portfolio as a result of this.",
  },
  {
    id: 17,
    img: "https://skillslash-cdn.s3.ap-south-1.amazonaws.com/static/web/GIRISH_BALLAMPALLI.webp",
    name: "Girisih",
    alt: "Girisih review",
    rating: "medium",
    para: " I think Dhaval has clear understanding of whatever he teach,wheher it is Data Structures, Algorithms, Dynamic Programming,",
    desc: "I think Dhaval has clear understanding of whatever he teach,wheher it is Data Structures, Algorithms, Dynamic Programming,  he explains with such ease that even hard problem seems easy. Hats off to his teaching and Dhaval keep on motivating and helping othersh really gave my preparation a solid boost.",
  },
  {
    id: 18,
    img: "https://skillslash-cdn.s3.ap-south-1.amazonaws.com/static/web/Anukalp_Desai.webp",
    name: "Anukalp Desai",
    alt: "Anukalp Desai review",
    rating: "low",
    para: "I have taken data structures and algorithms course taught by Dhaval, he is very accessible and does an amazing job at making",
    desc: "I have taken data structures and algorithms course taught by Dhaval, he is very accessible and does an amazing job at making difficult concepts easily understandable.",
  },
  {
    id: 19,
    img: "https://skillslash-cdn.s3.ap-south-1.amazonaws.com/static/web/Anurag_Sinha.webp",
    name: "Anurag Sinha",
    alt: "Anurag Sinha review",
    rating: "medium",
    para: "Dhawal Sir is a really great mentor. He helped me identify my weak areas and work on it consistently. He was always supportive and his style",
    desc: "Dhawal Sir is a really great mentor. He helped me identify my weak areas and work on it consistently. He was always supportive and his style  of teaching kept hinged to my goals. I was able to crack a senior software role as a result of that and I will always be thankful for all his support and guidance.",
  },
  {
    id: 20,
    img: "https://skillslash-cdn.s3.ap-south-1.amazonaws.com/static/web/Ankur_Singh.webp",
    name: "Ankur Singh",
    alt: "Ankur review",
    rating: "low",
    para: "The course structure was really good and covered most of the topics like Linked list, trees , graphs, recursion, dynamic programming etc.",
    desc: "The course structure was really good and covered most of the topics like Linked list, trees , graphs, recursion, dynamic programming etc.  Dhaval Sir did a great job taking each topic to a great clarity level. Rather than remembering the solution to the problem, he taught me how to approach problem and solve it.",
  },
];
