import React from "react";
import styles from "../../styles/ThankYou.module.css";
import Head from "next/head";
import Image from "next/image";

const ThankYou = () => {
  return (
    <div className={styles.main}>
      <Head>
        <title>Thank you</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <section className={styles.mains}>
        <div className={styles.left}>
          <h4 className={styles.hptop}>
            <b>Thank you</b>
            <br />
            for showing interest in the program
          </h4>
          <p className={styles.Ptop}>
            We have shared the program brochure with you over an email. Have a
            great day !
          </p>
          <div></div>
        </div>
        <div className={styles.right}>
          <Image
            src="https://skillslash-cdn.s3.ap-south-1.amazonaws.com/static/web/thank-you.png"
            alt="data-science-course"
            quality={100}
            width="500"
            height="550"
          />
        </div>
      </section>
    </div>
  );
};

export default ThankYou;
