export const DsProject = [
  {
    id: 1,
    domainName: "BFSI",
    title: "Predict Credit Default",
    alt: "predict credit default project for data science students",
    img: "https://skillslash-cdn.s3.ap-south-1.amazonaws.com/static/web/Moodys-Project.webp",
    desc: " Analyze a customer’s financial records, such as credit line number, age, payment history, and past 6 months’ delinquency history to forecast the likelihood of the customer’s default on future payments.     ",
    width: "107",
    height: "20",
  },
  {
    id: 2,
    domainName: "HealthCare",
    title: "Google Mobility data prediction",
    alt: "Work on realtime project with our data science projects",
    img: "https://skillslash-cdn.s3.ap-south-1.amazonaws.com/static/web/New-UI/Google_logo.webp",
    desc: " You will use historial Google mobility data, leveraging machine learning algorithms and statistical models to analyze future mobility patterns for insights into disease trends and behaviors.",
    width: "55",
    height: "32",
  },
  {
    id: 3,
    domainName: "Manufacturing and Supply Chain",
    title: "Material management and Planning for Factories",
    alt: "Work on realtime project with our use data science tools like powerBI",
    img: "https://skillslash-cdn.s3.ap-south-1.amazonaws.com/static/web/Uber.webp",
    desc: " Here, you will implement various advanced inventory management techniques, demand forecasting models, just-in-time practices and effective communication channels to aid coordination between the factory departments and minimize costs.",
    width: "70",
    height: "36",
  },
  {
    id: 4,
    domainName: "HealthCare",
    title: "Heart disease prediction ",
    alt: "work on real time data analysis use data science tools",
    img: "https://skillslash-cdn.s3.ap-south-1.amazonaws.com/static/web/proscia.webp",
    desc: " You will build a reliable machine learning model for predicting the risks of heart diseases on the basis of patient’s data, to aid early diagnosis and timely medical treatments.",
    width: "107",
    height: "20",
  },
  {
    id: 5,
    domainName: "HR",
    title: "Attrition Modeling to predict employee churn",
    alt: "use Data science techniques to solve analytics problems",
    img: "https://skillslash-cdn.s3.ap-south-1.amazonaws.com/static/web/Youtube.webp",
    desc: "You will build predictive models to anticipate potential attrition risks by analyzing historical data and enable measures to improve employee retention and organizational stability.",
    width: "107",
    height: "50",
  },
  {
    id: 6,
    domainName: "BFSI",
    title: "Foreign currency exchange rate prediction ",
    img: "https://skillslash-cdn.s3.ap-south-1.amazonaws.com/static/web/Bloombreg.webp",
    alt: "use Data science techniques to solve analytics problems",
    desc: "  Develop a reliable machine learning model for predicting foreign currency exchange rates while performing tasks of forecasting and time series analysis to make informed decisions in international financial transactions. ",
    width: "107",
    height: "20",
  },
  {
    id: 7,
    domainName: "BFSI",
    title: "Fraud detection for online / mobile banking services",
    alt: "use Data science techniques and tools to solve analytics problems",
    img: "https://skillslash-cdn.s3.ap-south-1.amazonaws.com/static/web/Razorpay.webp",
    desc: "You will implement advanced machine learning algorithms and anomaly detection  techniques to identify and prevent fraudulent activities that ensure the trust of customer’s financial transactions.",
    width: "107",
    height: "20",
  },
  {
    id: 29,
    domainName: "BFSI",
    title: "Designing an effective marketing strategy for banks",
    alt: "use Data science techniques and tools to solve analytics problems",
    img: "https://skillslash-cdn.s3.ap-south-1.amazonaws.com/static/web/Razorpay.webp",
    desc: "You will work to design an effective marketing strategy for banks that enhances customer acquisition, maximizes cross-selling opportunities, to drive sustainable growth and profitability for the institution.",
    width: "107",
    height: "20",
  },
  {
    id: 30,
    domainName: "BFSI",
    title: "Predicting dynamic interest rates on loans ",
    alt: "use Data science techniques and tools to solve analytics problems",
    img: "https://skillslash-cdn.s3.ap-south-1.amazonaws.com/static/web/Razorpay.webp",
    desc: "Create a predictive model with Ai technologies that allows financial institutions to help in  and organize  optimize lending strategies, manage risk effectively and offer transparent and competitive interest rates.",
    width: "107",
    height: "20",
  },

  {
    id: 8,
    domainName: "Manufacturing and Supply Chain",
    title: "Hazard/Fire detection in warehouses and factories ",
    alt: "mercedez logo",
    img: "https://skillslash-cdn.s3.ap-south-1.amazonaws.com/static/web/Mercedez.webp",
    desc: "You will be introduced to a combination of state-of-the-art sensors, computer vision and machine learning algorithms to identify and alert potential fire risks to ensure timely response.",
    width: "126",
    height: "32",
  },
  {
    id: 9,
    domainName: "Manufacturing and Supply Chain",
    title: "Route optimization and Loading strategies to reduce costs",
    alt: "mercedez logo",
    img: "https://skillslash-cdn.s3.ap-south-1.amazonaws.com/static/web/Mercedez.webp",
    desc: "The goal of this project is to implement efficient and effective routes and loading techniques using data analysis and algorithms to minimize transportation costs, travel distances and enhance logistical efficiency.",
    width: "126",
    height: "32",
  },

  {
    id: 10,
    domainName: "Manufacturing and Supply Chain",
    title:
      "Inventory management in warehouses through Object detection methods",
    alt: "lyft logo",
    img: "https://skillslash-cdn.s3.ap-south-1.amazonaws.com/static/web/lyft.webp",
    desc: "Implement and develop object detection methods to automatically identify and track items. Streamlining the inventory process and minimizing errors and manual effort.",
    width: "46",
    height: "20",
  },
  {
    id: 11,
    domainName: "HR",
    title: "Workforce management and planning",
    alt: "googleplay logo",
    img: "https://skillslash-cdn.s3.ap-south-1.amazonaws.com/static/web/Google-play.webp",
    desc: "Utilizing historical data, forecasting future workforce needs through affecting scheduling, resource allocating and alignment with business goals to reach maximum operational efficiency.",
    width: "110",
    height: "60",
  },

  {
    id: 14,
    domainName: "HealthCare",
    title: "Statistical Trials for diabetes treatment efficacy prediction",
    alt: "work on real time data analysis use data science tools",
    img: "https://skillslash-cdn.s3.ap-south-1.amazonaws.com/static/web/proscia.webp",
    desc: "Here, you will use in-depth experiments and statistical analysis to assess the effectiveness and safety of diabetes treatments to predict their effectiveness, manage and improve patient outcomes. ",
    width: "107",
    height: "20",
  },

  {
    id: 16,
    domainName: "Manufacturing and Supply Chain",
    title: "Predictive maintenance of machines",
    alt: "use Data science techniques and tools to solve analytics problems",
    img: "https://skillslash-cdn.s3.ap-south-1.amazonaws.com/static/web/Razorpay.webp",
    desc: "By analyzing real-time sensor data you will predict potential machine failures and perform maintenance actions. The goal being to reduce machine downtime and improve machine maintenance.",
    width: "107",
    height: "20",
  },

  {
    id: 32,
    domainName: "HR",
    title:
      "Predicting the Impact of HR Strategies through Prescriptive Analytics",
    alt: "soptify logo",
    img: "https://skillslash-cdn.s3.ap-south-1.amazonaws.com/static/web/soptify-logo.webp",
    desc: "Using prescriptive analysis, which involves analysis of historical data, identifying patterns and recommending optimal HR actions to improve employee performance and engagement.",
    width: "110",
    height: "60",
  },
  {
    id: 25,
    domainName: "Retail",
    title: "Amazon reviews for sentiment analysis",
    alt: "amazon logo",
    img: "https://skillslash-cdn.s3.ap-south-1.amazonaws.com/static/web/New-UI/amazon.png",
    desc: "You will analyze and categorize amazon reviews as positive, negative, or neutral by using natural language processing techniques to gauge customer satisfaction and sentiment towards products.",
    width: "93",
    height: "28",
  },
  {
    id: 27,
    domainName: "Retail",
    title: "Marketing Analytics",
    alt: "amazon logo",
    img: "https://skillslash-cdn.s3.ap-south-1.amazonaws.com/static/web/New-UI/amazon.png",
    desc: " The purpose of this project is to identify user behaviour patterns to effectively understand features that influence the sales.",
    width: "93",
    height: "28",
  },

  {
    id: "abs",
    domainName: "Retail",
    title: "Retail Sales prediction",
    alt: "amazon logo",
    img: "https://skillslash-cdn.s3.ap-south-1.amazonaws.com/static/web/New-UI/amazon.png",
    desc: "Using historical sales data and machine learning algorithms forecast future sales that enables retailers to optimize inventory and make informed business decisions for increased profitability.",
    width: "93",
    height: "28",
  },
  {
    id: "31",
    domainName: "Retail",
    title: "Marketing analytics for Website conversion analysis and tracking",
    alt: "amazon logo",
    img: "https://skillslash-cdn.s3.ap-south-1.amazonaws.com/static/web/New-UI/amazon.png",
    desc: "Identify key performance indicators through data analysis and tracking tools to measure website traffic, user engagement in order to create data-driven decisions and targeted marketing strategies.",
    width: "93",
    height: "28",
  },

  {
    id: "34",
    domainName: "Sales",
    title: "Market mix Models to gauge the efficiency of campaigns",
    alt: "amazon logo",
    img: "https://skillslash-cdn.s3.ap-south-1.amazonaws.com/static/web/New-UI/amazon.png",
    desc: "You will employ statistical techniques to analyze historical data and outcomes to build and apply Market Mix Models in order to measure the performance efficiency of campaigns, to optimize resource allocation.",
    width: "93",
    height: "28",
  },
  {
    id: "35",
    domainName: "Sales",
    title: "Sales Forecasting and Planning",
    alt: "amazon logo",
    img: "https://skillslash-cdn.s3.ap-south-1.amazonaws.com/static/web/New-UI/amazon.png",
    desc: "The goal is to develop and improve market performance and efforts by analyzing market trends, customer behavior, external factors and historical data to help meet demands effectively.",
    width: "93",
    height: "28",
  },
  {
    id: "36",
    domainName: "Sales",
    title: "Dashboarding for Sales Enablement",
    alt: "amazon logo",
    img: "https://skillslash-cdn.s3.ap-south-1.amazonaws.com/static/web/New-UI/amazon.png",
    desc: "The dashboarding process involves the process of data collection, integration and visualization using business intelligence tools to drive sales and revenue growth.",
    width: "93",
    height: "28",
  },
];
export const BaProject = [
  {
    id: 1,
    domainName: "BFSI",
    title: "Predict Credit Default",
    alt: "predict credit default project for data science students",
    img: "https://skillslash-cdn.s3.ap-south-1.amazonaws.com/static/web/Moodys-Project.webp",
    desc: " Analyze a customer’s financial records, such as credit line number, age, payment history, and past 6 months’ delinquency history to forecast the likelihood of the customer’s default on future payments.     ",
    width: "107",
    height: "20",
  },
  {
    id: 2,
    domainName: "HealthCare",
    title: "Google Mobility data prediction",
    alt: "Work on realtime project with our data science projects",
    img: "https://skillslash-cdn.s3.ap-south-1.amazonaws.com/static/web/New-UI/Google_logo.webp",
    desc: " You will use historial Google mobility data, leveraging machine learning algorithms and statistical models to analyze future mobility patterns for insights into disease trends and behaviors.",
    width: "55",
    height: "32",
  },
  {
    id: 3,
    domainName: "Manufacturing",
    title: "Material management and Planning for Factories",
    alt: "Work on realtime project with our use data science tools like powerBI",
    img: "https://skillslash-cdn.s3.ap-south-1.amazonaws.com/static/web/Uber.webp",
    desc: " Here, you will implement various advanced inventory management techniques, demand forecasting models, just-in-time practices and effective communication channels to aid coordination between the factory departments and minimize costs.",
    width: "70",
    height: "36",
  },
  {
    id: 4,
    domainName: "HealthCare",
    title: "Heart disease prediction ",
    alt: "work on real time data analysis use data science tools",
    img: "https://skillslash-cdn.s3.ap-south-1.amazonaws.com/static/web/proscia.webp",
    desc: " You will build a reliable machine learning model for predicting the risks of heart diseases on the basis of patient’s data, to aid early diagnosis and timely medical treatments.",
    width: "107",
    height: "20",
  },
  {
    id: 5,
    domainName: "HR",
    title: "Attrition Modeling to predict employee churn",
    alt: "use Data science techniques to solve analytics problems",
    img: "https://skillslash-cdn.s3.ap-south-1.amazonaws.com/static/web/Youtube.webp",
    desc: "You will build predictive models to anticipate potential attrition risks by analyzing historical data and enable measures to improve employee retention and organizational stability.",
    width: "107",
    height: "50",
  },
  {
    id: 6,
    domainName: "BFSI",
    title: "Foreign currency exchange rate prediction ",
    img: "https://skillslash-cdn.s3.ap-south-1.amazonaws.com/static/web/Bloombreg.webp",
    alt: "use Data science techniques to solve analytics problems",
    desc: "  Develop a reliable machine learning model for predicting foreign currency exchange rates while performing tasks of forecasting and time series analysis to make informed decisions in international financial transactions. ",
    width: "107",
    height: "20",
  },

  {
    id: 29,
    domainName: "BFSI",
    title: "Designing an effective marketing strategy for banks",
    alt: "use Data science techniques and tools to solve analytics problems",
    img: "https://skillslash-cdn.s3.ap-south-1.amazonaws.com/static/web/Razorpay.webp",
    desc: "You will work to design an effective marketing strategy for banks that enhances customer acquisition, maximizes cross-selling opportunities, to drive sustainable growth and profitability for the institution.",
    width: "107",
    height: "20",
  },

  {
    id: 9,
    domainName: "Manufacturing and Supply Chain",
    title: "Route optimization and Loading strategies to reduce costs",
    alt: "mercedez logo",
    img: "https://skillslash-cdn.s3.ap-south-1.amazonaws.com/static/web/Mercedez.webp",
    desc: "The goal of this project is to implement efficient and effective routes and loading techniques using data analysis and algorithms to minimize transportation costs, travel distances and enhance logistical efficiency.",
    width: "126",
    height: "32",
  },

  {
    id: 11,
    domainName: "HR",
    title: "Workforce management and planning",
    alt: "googleplay logo",
    img: "https://skillslash-cdn.s3.ap-south-1.amazonaws.com/static/web/Google-play.webp",
    desc: "Utilizing historical data, forecasting future workforce needs through affecting scheduling, resource allocating and alignment with business goals to reach maximum operational efficiency.",
    width: "110",
    height: "60",
  },
  {
    id: 12,
    domainName: "HR",
    title: "Resume parsing using NLP",
    alt: "soptify logo",
    img: "https://skillslash-cdn.s3.ap-south-1.amazonaws.com/static/web/soptify-logo.webp",
    desc: "Identifying and using Natural Language Processing techniques to analyze and interpret the textual content of resumes to create structured and actionable insights.",
    width: "110",
    height: "60",
  },
  {
    id: 13,
    domainName: "HealthCare",
    title: "Predictive Analytics in emergency care",
    alt: "work on real time data analysis use data science tools",
    img: "https://skillslash-cdn.s3.ap-south-1.amazonaws.com/static/web/project-facebook.webp",
    desc: "The goal is to enable healthcare providers to proactively allocate resources, and deliver optimized care timely by using data-driven models and machine learning algorithms to identify patient conditions",
    width: "107",
    height: "20",
  },
  {
    id: 14,
    domainName: "HealthCare",
    title: "Statistical Trials for diabetes treatment efficacy prediction",
    alt: "work on real time data analysis use data science tools",
    img: "https://skillslash-cdn.s3.ap-south-1.amazonaws.com/static/web/proscia.webp",
    desc: "Here, you will use in-depth experiments and statistical analysis to assess the effectiveness and safety of diabetes treatments to predict their effectiveness, manage and improve patient outcomes. ",
    width: "107",
    height: "20",
  },

  {
    id: 16,
    domainName: "Manufacturing and Supply Chain",
    title: "Predictive maintenance of machines",
    alt: "use Data science techniques and tools to solve analytics problems",
    img: "https://skillslash-cdn.s3.ap-south-1.amazonaws.com/static/web/Razorpay.webp",
    desc: "By analyzing real-time sensor data you will predict potential machine failures and perform maintenance actions. The goal being to reduce machine downtime and improve machine maintenance.",
    width: "107",
    height: "20",
  },
  {
    id: 17,
    domainName: "HR",
    title: "Predicting and improving the mental health",
    alt: "soptify logo",
    img: "https://skillslash-cdn.s3.ap-south-1.amazonaws.com/static/web/soptify-logo.webp",
    desc: "Predict and improve the mental health and satisfaction of employees by using data analysis and implementing target support systems to create a positive work environment",
    width: "110",
    height: "60",
  },
  {
    id: 32,
    domainName: "HR",
    title:
      "Predicting the Impact of HR Strategies through Prescriptive Analytics",
    alt: "soptify logo",
    img: "https://skillslash-cdn.s3.ap-south-1.amazonaws.com/static/web/soptify-logo.webp",
    desc: "Using prescriptive analysis, which involves analysis of historical data, identifying patterns and recommending optimal HR actions to improve employee performance and engagement.",
    width: "110",
    height: "60",
  },

  {
    id: 27,
    domainName: "Retail",
    title: "Marketing Analytics",
    alt: "amazon logo",
    img: "https://skillslash-cdn.s3.ap-south-1.amazonaws.com/static/web/New-UI/amazon.png",
    desc: " The purpose of this project is to identify user behaviour patterns to effectively understand features that influence the sales.",
    width: "93",
    height: "28",
  },
  {
    id: 28,
    domainName: "Retail",
    title: "Recommender Systems",
    alt: "amazon logo",
    img: "https://skillslash-cdn.s3.ap-south-1.amazonaws.com/static/web/New-UI/amazon.png",
    desc: "Enhance user experience and increase engagement in various domains of e-commerce, content and online platforms. Learn and use data mining, collaborative filtering and machine learning techniques to predict user preferences.",
    width: "93",
    height: "28",
  },
  {
    id: "abs",
    domainName: "Retail",
    title: "Retail Sales prediction",
    alt: "amazon logo",
    img: "https://skillslash-cdn.s3.ap-south-1.amazonaws.com/static/web/New-UI/amazon.png",
    desc: "Using historical sales data and machine learning algorithms forecast future sales that enables retailers to optimize inventory and make informed business decisions for increased profitability.",
    width: "93",
    height: "28",
  },
  {
    id: "31",
    domainName: "Retail",
    title: "Marketing analytics for Website conversion analysis and tracking",
    alt: "amazon logo",
    img: "https://skillslash-cdn.s3.ap-south-1.amazonaws.com/static/web/New-UI/amazon.png",
    desc: "Identify key performance indicators through data analysis and tracking tools to measure website traffic, user engagement in order to create data-driven decisions and targeted marketing strategies.",
    width: "93",
    height: "28",
  },
  {
    id: "33",
    domainName: "Sales",
    title: "Analyzing Google Analytics to track customer interactions",
    alt: "amazon logo",
    img: "https://skillslash-cdn.s3.ap-south-1.amazonaws.com/static/web/New-UI/amazon.png",
    desc: "Optimizing user experience by integrating Google analytics with the website and collecting and interpreting user data to understand user preferences, patterns and engagements with the site’s content and features",
    width: "93",
    height: "28",
  },
  {
    id: "34",
    domainName: "Sales",
    title: "Market mix Models to gauge the efficiency of campaigns",
    alt: "amazon logo",
    img: "https://skillslash-cdn.s3.ap-south-1.amazonaws.com/static/web/New-UI/amazon.png",
    desc: "You will employ statistical techniques to analyze historical data and outcomes to build and apply Market Mix Models in order to measure the performance efficiency of campaigns, to optimize resource allocation.",
    width: "93",
    height: "28",
  },
  {
    id: "35",
    domainName: "Sales",
    title: "Sales Forecasting and Planning",
    alt: "amazon logo",
    img: "https://skillslash-cdn.s3.ap-south-1.amazonaws.com/static/web/New-UI/amazon.png",
    desc: "The goal is to develop and improve market performance and efforts by analyzing market trends, customer behavior, external factors and historical data to help meet demands effectively.",
    width: "93",
    height: "28",
  },
  {
    id: "36",
    domainName: "Sales",
    title: "Dashboarding for Sales Enablement",
    alt: "amazon logo",
    img: "https://skillslash-cdn.s3.ap-south-1.amazonaws.com/static/web/New-UI/amazon.png",
    desc: "The dashboarding process involves the process of data collection, integration and visualization using business intelligence tools to drive sales and revenue growth.",
    width: "93",
    height: "28",
  },
  {
    id: "37",
    domainName: "Sales",
    title: "Promotion modeling to quantify the impact of discounts/promotions ",
    alt: "amazon logo",
    img: "https://skillslash-cdn.s3.ap-south-1.amazonaws.com/static/web/New-UI/amazon.png",
    desc: "Utilizing multiple machine learning and statistical techniques to analyze the past promotional data and predict the outcome and impact of future promotions.",
    width: "93",
    height: "28",
  },
];
export const FsProject = [
  {
    id: 1,
    title: "Authentication",
    alt: "cisco logo",
    img: "https://skillslash-cdn.s3.ap-south-1.amazonaws.com/static/web/New-UI/cisco.webp",
    desc: "  Create authentication technology to give access, Correspond to those    stored in a database of authorized users.",
    width: "220",
    height: "37",
  },
  {
    id: 2,
    title: "CRUD",
    alt: "sql logo",
    img: "https://skillslash-cdn.s3.ap-south-1.amazonaws.com/static/web/New-UI/sql.webp",
    desc: " Create an online tool that allows users to edit, delete, and add    records while viewing the database's contents in list format.",
    width: "170",
    height: "35",
  },
  {
    id: 3,
    title: "Video Conferencing App",
    alt: "do full stack projects with our full stack developer course likee google meet logo",
    img: "https://skillslash-cdn.s3.ap-south-1.amazonaws.com/static/web/New-UI/gmeet.webp",
    desc: "This is an innovative full-stack web development project with    seamless audio-video call management capabilities.",
    width: "280",
    height: "35",
  },
  {
    id: 4,
    title: "API Integration",
    alt: "do the api intregration with full stack course like accuweather",
    img: "https://skillslash-cdn.s3.ap-south-1.amazonaws.com/static/web/New-UI/accuweather.webp",
    desc: "  Cardiovascular diseases (CVDs) are the number 1 cause of death    globally. So here have to create a model that could predict heart    failure before its occurrence.",
    width: "230",
    height: "37",
  },
  {
    id: 5,
    title: "Payment Gateway",
    alt: "build a payment gateway google pay",
    img: "https://skillslash-cdn.s3.ap-south-1.amazonaws.com/static/web/New-UI/gpay.webp",
    desc: "  Learn how to integrate the payment gateway that online businesses    use to authorise and process credit card and debit payments.",
    width: "212",
    height: "33",
  },
  {
    id: 6,
    title: "Travel Booking Application",
    alt: "build a travel booking project with our full stack course like happay logo",
    img: "https://skillslash-cdn.s3.ap-south-1.amazonaws.com/static/web/New-UI/happay.webp",
    desc: "   The associated website must provide registration, login and logout,    and profile building and modification.",
    width: "234",
    height: "42",
  },
  {
    id: 7,
    title: "Workout Application",
    alt: "trx logo",
    img: "https://skillslash-cdn.s3.ap-south-1.amazonaws.com/static/web/New-UI/trx.webp",
    desc: "  Modern fitness monitors go much beyond the standard pedometer. Users' heart rates and run times are tracked and stored.",
    width: "135",
    height: "25",
  },
  {
    id: 8,
    title: "Blog Site",
    alt: "wix logo",
    img: "https://skillslash-cdn.s3.ap-south-1.amazonaws.com/static/web/New-UI/wix.webp",
    desc: "   Create a CMS website or application which has a better content    optimization and visuals optimization.",
    width: "50",
    height: "19",
  },
  {
    id: 9,
    title: "Home Service Application",
    alt: "codiant logo",
    img: "https://skillslash-cdn.s3.ap-south-1.amazonaws.com/static/web/New-UI/codiant.webp",
    desc: "  Local services will be listed on this website. Local businesses and    services can promote their offerings, pricing, and locations.",
    width: "250",
    height: "26",
  },
  {
    id: 10,
    title: "VR Based Application",
    alt: "cryenine logo",
    img: "https://skillslash-cdn.s3.ap-south-1.amazonaws.com/static/web/New-UI/cryengine.webp",
    desc: "Make a VR programme with enhanced audiovisual capabilities. Learn    how to use VR applications to relieve anxiety and tension.",
    width: "277",
    height: "26",
  },
  {
    id: 11,
    title: "To-Do List Application",
    alt: "Task logo",
    img: "https://skillslash-cdn.s3.ap-south-1.amazonaws.com/static/web/New-UI/task.webp",
    desc: "  You will get knowledge about creating and improving multi-use panels    and components through this project.",
    width: "200",
    height: "24",
  },
  {
    id: 12,
    title: "Food Delivery Application",
    alt: "swiggy logo",
    img: "https://skillslash-cdn.s3.ap-south-1.amazonaws.com/static/web/New-UI/swiggy.webp",
    desc: "  Create a sizable, feature-rich meal delivery website through this    project. Build a backend framework for restaurant registration.",
    width: "200",
    height: "24",
  },
  {
    id: 13,
    title: "Chatting/Messaging App",
    alt: "telegram logo",
    img: "  https://skillslash-cdn.s3.ap-south-1.amazonaws.com/static/web/New-UI/telegram.png",
    desc: " Create a decent- looking and incredibly functional front- end. This    project focuses on creating a user- friendly chat applications.",
    width: "85",
    height: "23",
  },
  {
    id: 14,
    title: "Stock Investment App",
    alt: "centra logo",
    img: "  https://skillslash-cdn.s3.ap-south-1.amazonaws.com/static/web/New-UI/centra.webp",
    desc: " You will get knowledge about creating and improving multi-use panels     and components through this project.",
    width: "169",
    height: "24",
  },
  {
    id: 15,
    title: "Online Code Editor",
    alt: "leetcode logo",
    img: " https://skillslash-cdn.s3.ap-south-1.amazonaws.com/static/web/New-UI/leetcode.webp",
    desc: "  Your attention will be drawn to prototyping, quick hosting of newly    published apps, and seamless collaboration.",
    width: "200",
    height: "24",
  },
];
export const webProject = [
  {
    id: 1,
    title: "Retail",
    img: "https://skillslash-cdn.s3.ap-south-1.amazonaws.com/static/web/New-UI/amazon-flipkart-ecommerce-project.webp",
    alt: "learn git and many tools and build Retail project like flipkart,amazon",
    desc: " Create a dynamic and responsive environment.Retail web application using technologies such as Angular, Hibernate,MySQL, and Docker.",
    width: "200",
    height: "34",
  },
  {
    id: 2,
    title: "Chatbot Application",
    alt: "work web development projects and develop chat bot application",
    img: "https://skillslash-cdn.s3.ap-south-1.amazonaws.com/static/web/New-UI/slush-icon.webp",
    desc: "Chatbots are computer programmes that mimic spoken or written language. So these mimic communication or contact with a real person.",
    width: "200",
    height: "34",
  },
  {
    id: 3,
    title: "Show Booking App",
    alt: "become a full stack web developer work on project like bookmyshow",
    img: "https://skillslash-cdn.s3.ap-south-1.amazonaws.com/static/web/New-UI/bookmyshow.webp",
    desc: "   Create an entertainment application like BookMyShow using your back-end knowledge, API development, and HTML and CSS skills.",
    width: "200",
    height: "34",
  },
  {
    id: 4,
    title: "Courier Tracking System",
    alt: "prohance logo",
    img: "https://skillslash-cdn.s3.ap-south-1.amazonaws.com/static/web/New-UI/prohance.webp",
    desc: " Contains information about both administrator and user functions, including office registration, creating users, viewing suggestions and complaints of users.",
    width: "266",
    height: "42",
  },
  {
    id: 5,
    title: "Fuel Delivery Flutter App",
    alt: "fuelbody logo",
    img: "https://skillslash-cdn.s3.ap-south-1.amazonaws.com/static/web/New-UI/fuelbody.webp",
    desc: "   When it comes to refilling their vehicles, businesses who manage a fleet of vehicles, such as taxi and cab firms,intercity and long-distance bus service providers, trucking agencies, etc., frequently run into problems.",
    width: "83",
    height: "25",
  },

  {
    id: 8,
    title: "Online Examination System",
    alt: "synap logo",
    img: "https://skillslash-cdn.s3.ap-south-1.amazonaws.com/static/web/New-UI/synap.webp",
    desc: "    The online examination system, which is adopted by an increasing number of schools not only shows the validity and impartiality of examinations of some of their workload.",
    width: "200",
    height: "34",
  },
  {
    id: 9,
    title: "Sorting Visualizer",
    alt: "sortilizer logo",
    img: "https://skillslash-cdn.s3.ap-south-1.amazonaws.com/static/web/New-UI/sortilizer.webp",
    desc: " This is the ideal project for you if you're looking for a fresh JavaScript project concept, want to learn JavaScript inside and out, or want to advance your JavaScript abilities.",
    width: "85",
    height: "21",
  },

  {
    id: 11,
    title: "Food Delivery App",
    alt: "swiggy logo",
    img: "https://skillslash-cdn.s3.ap-south-1.amazonaws.com/static/web/New-UI/swiggy.webp",
    desc: " Build a food delivery app from scratch using your knowledge of the Spring framework, web services, and MySQL with a strong back-end to support operations. Learn to use latest frameworks",
    width: "200",
    height: "34",
  },
  {
    id: 12,
    title: "Social Media Applications",
    alt: "facebook logo",
    img: "https://skillslash-cdn.s3.ap-south-1.amazonaws.com/static/web/New-UI/facebook.webp",
    desc: "  Immersing yourself in the field of socializing, hanging outwith friends and chilling. Build a full stack application like instagram and facebook.",
    width: "174",
    height: "47",
  },
];
